#!/bin/sh
g++ \
  -I/usr/local/pyside/include/PySide/ \
  -I/usr/local/pyside/include/shiboken/ \
  -I/usr/local/pyside/include/PySide/QtCore/ \
  -I/usr/local/pyside/include/PySide/QtGui/ \
  -I/usr/local/pyside/include/PySide/QtOpenGL/ \
  -I/usr/include/Qt \
  -I/usr/include/QtCore \
  -I/usr/include/QtGui \
  -I/usr/local/include/python2.7 \
  -IDFG/ \
  -IGraphView/ \
  -IKLEditor/ \
  -ILicensing/ \
  -ISceneHub/ \
  -IStyle/ \
  -ITreeView/ \
  -IValueEditor/ \
  -IViewports/ \
  -Ishiboken/ \
  -Iout/FabricUI/ \
  -I. \
  -I../.. \
  -I../FabricServices/ \
  -I../../stage/Linux/x86_64/Release/include/ \
  -L/usr/local/pyside/lib \
  -L../../stage/Linux/x86_64/Release/lib \
  -g -O0 \
  -fPIC -DFEC_PROVIDE_STL_BINDINGS -DFEC_SHARED -shared -o FabricUI.so out/FabricUI/*.cpp \
  -lFabricUI \
  -lFabricServices \
  -lFabricSplitSearch \
  -lFabricCore \
  -lQtCore \
  -lQtGui \
  -lQtOpenGL \
  -lpyside-python2.7 \
  -lshiboken-python2.7
